---
title: "Final Project"
output: html_document
author: "Cole Weber, Juan Simons, Jacob Baalson, Charles Whiting"
date: "4/3/2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


The names of team members & project coordinator:   

Cole Weber (Project coordinator), Juan Simons, Jacob Baalson, Charles Whiting     


The link to the data source:   

https://www.kaggle.com/sobhanmoosavi/us-accidents

An overview of the dataset:   

This dataset contains car accident information from 49 states in the US. This data was collected from February 2016 to December 2019. The two main data sources for the dataset was MapQuest and Bing. There are 3.0 million accident records in the dataset.   

Citations:   

Moosavi, Sobhan, Mohammad Hossein Samavatian, Srinivasan Parthasarathy, and Rajiv Ramnath. “A Countrywide Traffic Accident Dataset.”, 2019.     

Moosavi, Sobhan, Mohammad Hossein Samavatian, Srinivasan Parthasarathy, Radu Teodorescu, and Rajiv Ramnath. "Accident Risk Prediction based on Heterogeneous Sparse Data: New Dataset and Insights." In proceedings of the 27th ACM SIGSPATIAL International Conference on Advances in Geographic Information Systems, ACM, 2019.   

A brief plan for an exploratory analysis: What questions can be answered from the dataset?    

-What were the most common weather conditions during accidents?    
-Does the size of a city affect traffic accident rate during rush hour times?    
-What states have the most severe accidents?    
-How do different seasons affect crash rates among states?    
-How do the most populated cities (Des Moines, Cedar Rapids, Davenport) in Iowa compare in traffic accident rate?    
-Which year had the highest amount of accidents and did weather conditions affect those statistics?    
-Is there a difference between night and day in the rate of accidents and total accidents?    
-Does the size of the city affect the severity of the traffic delays?   